from pathlib import Path

import pytest

from backend.src.schemas.resource import ResourceType

def test_e2e_vm_single_provider_azure_new():
    import csv
    import subprocess
    import sys

    test_data_folder = Path(__file__).parent / "test_data"
    output_dir = test_data_folder / "output"
    output_dir.mkdir(parents=True, exist_ok=True)

    # Ensure deterministic assertion by removing previous report artifacts.
    for old_report in output_dir.glob("CO2_*.csv"):
        old_report.unlink()

    main_config_path = test_data_folder / "config" / "config.yaml"

    project_root = Path(__file__).resolve().parents[5]
    command = [
        sys.executable,
        "-m",
        "backend.src.daemon.carbon_daemon_orchestrator",
        "--carmen-config-filepath",
        str(main_config_path),
        "--carmen-provider-config-filepath",
        str(test_data_folder / "config" / "modelling_constants" / "cloud_providers"),
        "--carmen-carbon-values-filepath",
        str(test_data_folder / "config" / "modelling_constants" / "carbon_values.yaml"),
    ]
    daemon = subprocess.run(
        command,
        cwd=project_root,
        capture_output=True,
        text=True,
        check=False,
    )
    assert daemon.returncode == 0, (
        f"Daemon main failed with exit code {daemon.returncode}\n"
        f"STDOUT:\n{daemon.stdout}\nSTDERR:\n{daemon.stderr}"
    )

    reports = sorted(output_dir.glob("CO2_*.csv"))
    assert reports, "No output CSV report generated by daemon main"

    with open(reports[-1], "r", encoding="utf-8") as report_f:
        rows_out = list(csv.DictReader(report_f))

    assert len(rows_out) == 1
    row = rows_out[0]
    assert row["ResourceType"] == ResourceType.VIRTUAL_MACHINE.value
    assert row["VMSize"] == "Standard_A1_v2"
    assert row["Provider"] == "azure"
    assert row["Region"] == "eastus"

    # Keep expected values aligned with the pre-existing single-VM e2e scenario.
    assert float(row["EnergyKWH"]) == pytest.approx(0.0031, rel=1e-3)
    assert float(row["OperationalCarbonGramsCO2eq"]) == pytest.approx(1.1775, rel=1e-3)
    assert float(row["EmbodiedCarbonGramsCO2eq"]) == pytest.approx(1.4254, rel=1e-3)
    assert float(row["TotalCarbonGramsCO2eq"]) == pytest.approx(2.6029, rel=1e-3)
