from pathlib import Path

import pytest

from backend.src.schemas.resource import ResourceType

def test_e2e_vm_single_provider_azure():
    import csv
    import subprocess
    import sys

    test_data_folder = Path(__file__).parent / "test_data"
    output_dir = test_data_folder / "output"
    output_dir.mkdir(parents=True, exist_ok=True)

    # Ensure deterministic assertion by removing previous report artifacts.
    for old_report in output_dir.glob("CO2_*.csv"):
        old_report.unlink()

    main_config_path = test_data_folder / "config" / "config.yaml"

    project_root = Path(__file__).resolve().parents[5]
    command = [
        sys.executable,
        "-m",
        "backend.src.daemon.carbon_daemon_orchestrator",
        "--carmen-config-filepath",
        str(main_config_path),
        "--carmen-provider-config-filepath",
        str(test_data_folder / "config" / "modelling_constants" / "cloud_providers"),
        "--carmen-carbon-values-filepath",
        str(test_data_folder / "config" / "modelling_constants" / "carbon_values.yaml"),
    ]
    daemon = subprocess.run(
        command,
        cwd=project_root,
        capture_output=True,
        text=True,
        check=False,
    )
    assert daemon.returncode == 0, (
        f"Daemon main failed with exit code {daemon.returncode}\n"
        f"STDOUT:\n{daemon.stdout}\nSTDERR:\n{daemon.stderr}"
    )

    reports = sorted(output_dir.glob("CO2_*.csv"))
    assert reports, "No output CSV report generated by daemon main"

    with open(reports[-1], "r", encoding="utf-8") as report_f:
        rows_out = list(csv.DictReader(report_f))

    assert len(rows_out) == 1
    row = rows_out[0]
    assert row["ResourceType"] == ResourceType.VIRTUAL_MACHINE.value
    assert row["VMSize"] == "Standard_A1_v2"
    assert row["Provider"] == "azure"
    assert row["Region"] == "eastus"

    # ── Carbon/energy computation derivation ─────────────────────────────────
    #
    # Input data  (3 hourly time points for vm-01, all merged into one resource)
    #   T00: cpu_util=20%, T01: cpu_util=20%, T02: cpu_util=100%
    #   VmDiskSizeGb=128 GB  (all 3 rows)
    #
    # Instance hardware  (azure_instances.csv – Standard_A1_v2)
    #   cpu-cores-available=52, cpu-cores-utilized=1, cpu-tdp=205 W, memory=2 GB
    #   vm_tdp = 205 × (1/52) = 3.9423 W   ← TDP scaled to the allocated core share
    #
    # duration = HOURLY_INTERVAL_SECONDS = 3600 s per observation
    #
    # ── Energy per observation (SCI-E pipeline) ──────────────────────────────
    #
    # 1. TeadsCurve – linear interpolation [0,10,50,100]% → [0.12,0.32,0.75,1.02]
    #    tdp_ratio(20%)  = 0.32 + (20-10)/(50-10) × (0.75-0.32) = 0.4275
    #    tdp_ratio(100%) = 1.02   (exact control point)
    #
    # 2. cpu/power (kW) = tdp_ratio × vm_tdp / 1000
    #    T00,T01: 0.4275 × 3.9423 / 1000 = 0.001685 kW
    #    T02:     1.02   × 3.9423 / 1000 = 0.004021 kW
    #
    # 3. cpu/energy (kWh) = cpu/power × 3600 s / 3600 = cpu/power (1-hour window)
    #    T00,T01: 0.001685 kWh   T02: 0.004021 kWh
    #
    # 4. memory/power  = 2.0 GB × 0.000392 kW/GB = 0.000784 kW   (PMem, CCF)
    #    memory/energy = 0.000784 × 3600/3600     = 0.000784 kWh  (all obs.)
    #
    # 5. storage/power  = 128 GB × 9.25e-7 kW/GB = 1.184e-4 kW   (PVmStorage)
    #    storage/energy  = 1.184e-4 × 3600/3600   = 1.184e-4 kWh  (all obs.)
    #
    # 6. energy_raw = cpu/energy + memory/energy + storage/energy  (SciE sum)
    #    T00,T01: 0.001685 + 0.000784 + 0.000118 = 0.002588 kWh
    #    T02:     0.004021 + 0.000784 + 0.000118 = 0.004924 kWh
    #
    # 7. energy (kWh) = energy_raw × PUE  (SciEPue, azure PUE=1.185)
    #    T00,T01: 0.002588 × 1.185 = 0.003066 kWh
    #    T02:     0.004924 × 1.185 = 0.005834 kWh
    #    ─────────────────────────────────────────
    #    TOTAL EnergyKWH = 0.003066 + 0.003066 + 0.005834 = 0.012 kWh
    #
    # ── Operational carbon (SciO) ────────────────────────────────────────────
    #
    #    carbon-operational = energy × carbon_intensity
    #    carbon_intensity(eastus) = 384 gCO2/kWh  (United_States, carbon_values.yaml)
    #    T00,T01: 0.003066 × 384 = 1.1775 gCO2e
    #    T02:     0.005834 × 384 = 2.2404 gCO2e
    #    ─────────────────────────────────────────
    #    TOTAL OperationalCarbonGramsCO2eq = 1.1775 + 1.1775 + 2.2404 = 4.5955 gCO2e
    #
    # ── Embodied carbon (SciM pipeline) ─────────────────────────────────────
    #
    #    CPU embodied (sci-m-cpu / @grnsft/if-plugins SciM):
    #      = device_embodied × (duration / expected_lifespan) × (vcpus_allocated / vcpus_total)
    #      = 1999999 × (3600 / 126230400) × (1 / 52) = 1.0969 gCO2e per obs.
    #      (device/emissions-embodied=1999999 treated as gCO2e by the SciM plugin,
    #       device/expected-lifespan=126230400 s = 4 years)
    #
    #    Storage embodied (m-vm-storage):
    #      = storage/requested × storage/embodied-coefficient × duration / expected_lifespan
    #      = 128 × 90 × 3600 / 126230400 = 0.3285 gCO2e per obs.
    #      (storage/embodied-coefficient=90 gCO2e/GB, unknown/default)
    #
    #    Total per obs.: 1.0969 + 0.3285 = 1.4254 gCO2e  (same for all 3, embodied is time-independent)
    #    ─────────────────────────────────────────
    #    TOTAL EmbodiedCarbonGramsCO2eq = 3 × 1.4254 = 4.2763 gCO2e
    #
    # ── Total carbon ─────────────────────────────────────────────────────────
    #    TOTAL TotalCarbonGramsCO2eq = 4.5955 + 4.2763 = 8.8718 gCO2e
    # ─────────────────────────────────────────────────────────────────────────

    assert float(row["EnergyKWH"]) == pytest.approx(0.012, rel=1e-3)
    assert float(row["OperationalCarbonGramsCO2eq"]) == pytest.approx(4.5955, rel=1e-3)
    assert float(row["EmbodiedCarbonGramsCO2eq"]) == pytest.approx(4.2763, rel=1e-3)
    assert float(row["TotalCarbonGramsCO2eq"]) == pytest.approx(8.8718, rel=1e-3)
