
# Carbon intensity per location
# 2024 Data (Source: https://ourworldindata.org/grapher/carbon-intensity-electricity)
# CSP region → location mapping is defined in each provider's YAML config.
# The fallback default carbon_intensity value is defined in config.yaml under defaults.
# Add new countries at the end of the file.

carbon_intensity_by_location:
  Australia:
    carbon_intensity: 552
  Hong_Kong:
    carbon_intensity: 560
  United_States:
    carbon_intensity: 384
  France:
    carbon_intensity: 44
  Germany:
    carbon_intensity: 344
  Ireland:
    carbon_intensity: 280
  Singapore:
    carbon_intensity: 499
  Sweden:
    carbon_intensity: 36
  Dubai:
    carbon_intensity: 493
  United_Kingdom:
    carbon_intensity: 211
  Netherlands:
    carbon_intensity: 253
  India:
    carbon_intensity: 708

# in gCO2e/GB from https://hotcarbon.org/assets/2022/pdf/hotcarbon22-tannu.pdf
storage_embodied:
  ssd: 160
  hdd: 20
  unknown: 90  # Average
