"""Shared helpers for daemon E2E tests."""

from __future__ import annotations

import pytest

from backend.src.schemas.resource import ResourceType

common_fields_str = [
    "ResourceType",
    "Provider",
    "Region",
]

common_fields_float = [
    "EnergyKWH",
    "OperationalCarbonGramsCO2eq",
    "EmbodiedCarbonGramsCO2eq",
    "TotalCarbonGramsCO2eq",
    "CarbonIntensity",
]

VM_fields = [
    "VMSize",
]

storage_fields = [
    "StorageType",
    "ReplicationType",
    "SizeGB",
]

def validate_output(row_by_id, expected_result_by_id):
    for resource_id, expected_result in expected_result_by_id.items():
        actual_result = row_by_id.get(resource_id)
        assert actual_result is not None, f"Missing output row for resource {resource_id}"

        # Validate fields only if they are present in the expected result
        # This allows for partial validation of the output rows

        # Validate string fields
        for field in common_fields_str:
            if field in expected_result:
                assert actual_result[field] == expected_result[field], f"{resource_id}: {field} actual_result={actual_result[field]} expected_result={expected_result[field]}"

        # Validate float fields
        for field in common_fields_float:
            if field in expected_result:
                assert float(actual_result[field]) == pytest.approx(expected_result[field], rel=1e-3), (
                    f"{resource_id}: {field} actual_result={actual_result[field]} expected_result={expected_result[field]}"
            )
                
        if expected_result["ResourceType"] == ResourceType.VIRTUAL_MACHINE.value:
            for field in VM_fields:
                # By default, VMSize is a string, so we can compare directly
                if field in expected_result:
                    assert actual_result[field] == expected_result[field], f"{resource_id}: {field} actual_result={actual_result[field]} expected_result={expected_result[field]}"

        if expected_result["ResourceType"] == ResourceType.STORAGE.value:
            for field in storage_fields:
                # Float comparison
                if field == "SizeGB":
                    assert float(actual_result[field]) == pytest.approx(expected_result[field], rel=1e-6), (
                        f"{resource_id}: {field} actual_result={actual_result[field]} expected_result={expected_result[field]}"
                    )
                # String comparison
                else:
                    assert actual_result[field] == expected_result[field], f"{resource_id}: {field} actual_result={actual_result[field]} expected_result={expected_result[field]}"

def run_daemon(test_path):
    import csv
    import subprocess
    import sys
    test_data_folder = test_path.parent / "test_data"
    output_dir = test_path.parent / "test_data" / "output"
    output_dir.mkdir(parents=True, exist_ok=True)

    # Ensure deterministic assertion by removing previous report artifacts.
    for old_report in output_dir.glob("CO2_*.csv"):
        old_report.unlink()

    main_config_path = test_data_folder / "config" / "config.yaml"

    project_root = test_path.resolve().parents[5]
    command = [
        sys.executable,
        "-m",
        "backend.src.daemon.carbon_daemon_orchestrator",
        "--carmen-config-filepath",
        str(main_config_path),
        "--carmen-provider-config-filepath",
        str(test_data_folder / "config" / "modelling_constants" / "cloud_providers"),
        "--carmen-carbon-values-filepath",
        str(test_data_folder / "config" / "modelling_constants" / "carbon_values.yaml"),
    ]
    daemon = subprocess.run(
        command,
        cwd=project_root,
        capture_output=True,
        text=True,
        check=False,
    )
    assert daemon.returncode == 0, (
        f"Daemon main failed with exit code {daemon.returncode}\n"
        f"STDOUT:\n{daemon.stdout}\nSTDERR:\n{daemon.stderr}"
    )

    reports = sorted(output_dir.glob("CO2_*.csv"))
    assert reports, "No output CSV report generated by daemon main"

    with open(reports[-1], "r", encoding="utf-8") as report_f:
        return list(csv.DictReader(report_f))
