"""Shared helpers for daemon E2E tests."""

from __future__ import annotations

import pytest

from backend.src.schemas.resource import ResourceType

def validate_output(row_by_id, expected_by_id):
    for resource_id, expected in expected_by_id.items():
        row = row_by_id.get(resource_id)
        assert row is not None, f"Missing output row for resource {resource_id}"

        # Subtest by resource row: each produced row is validated independently.
        assert row["ResourceType"] == expected["ResourceType"], resource_id
        assert row["Provider"] == expected["Provider"], resource_id
        assert row["Region"] == expected["Region"], resource_id

        assert float(row["EnergyKWH"]) == pytest.approx(expected["EnergyKWH"], rel=1e-3), resource_id
        assert float(row["OperationalCarbonGramsCO2eq"]) == pytest.approx(
            expected["OperationalCarbonGramsCO2eq"], rel=1e-3
        ), resource_id
        assert float(row["EmbodiedCarbonGramsCO2eq"]) == pytest.approx(
            expected["EmbodiedCarbonGramsCO2eq"], rel=1e-3
        ), resource_id
        assert float(row["TotalCarbonGramsCO2eq"]) == pytest.approx(
            expected["TotalCarbonGramsCO2eq"], rel=1e-3
        ), resource_id
        
        if expected["ResourceType"] == ResourceType.STORAGE.value:
            assert row["StorageType"] == expected["StorageType"], resource_id
            assert row["ReplicationType"] == expected["ReplicationType"], resource_id
            assert float(row["SizeGB"]) == pytest.approx(expected["SizeGB"], rel=1e-6), resource_id
        
def run_daemon(test_path):
    import csv
    import subprocess
    import sys
    test_data_folder = test_path.parent / "test_data"
    output_dir = test_path.parent / "test_data" / "output"
    output_dir.mkdir(parents=True, exist_ok=True)

    # Ensure deterministic assertion by removing previous report artifacts.
    for old_report in output_dir.glob("CO2_*.csv"):
        old_report.unlink()

    main_config_path = test_data_folder / "config" / "config.yaml"

    project_root = test_path.resolve().parents[5]
    command = [
        sys.executable,
        "-m",
        "backend.src.daemon.carbon_daemon_orchestrator",
        "--carmen-config-filepath",
        str(main_config_path),
        "--carmen-provider-config-filepath",
        str(test_data_folder / "config" / "modelling_constants" / "cloud_providers"),
        "--carmen-carbon-values-filepath",
        str(test_data_folder / "config" / "modelling_constants" / "carbon_values.yaml"),
    ]
    daemon = subprocess.run(
        command,
        cwd=project_root,
        capture_output=True,
        text=True,
        check=False,
    )
    assert daemon.returncode == 0, (
        f"Daemon main failed with exit code {daemon.returncode}\n"
        f"STDOUT:\n{daemon.stdout}\nSTDERR:\n{daemon.stderr}"
    )

    reports = sorted(output_dir.glob("CO2_*.csv"))
    assert reports, "No output CSV report generated by daemon main"

    with open(reports[-1], "r", encoding="utf-8") as report_f:
        return list(csv.DictReader(report_f))